version: 2
updates:
  # Configuração para dependências de JavaScript e Node.js
  - package-ecosystem: "npm" 
    directory: "/" # Onde o arquivo package.json está (raiz do projeto)
    schedule:
      interval: "weekly" # Frequência de checagem (semanal)
      
    # Configuração de rótulos e limites (Opcional, mas recomendado)
    labels:
      - "dependabot"
      - "dependencias"
    open-pull-requests-limit: 10 # Limita a 10 Pull Requests abertos por vez
